"""Perhaps migrations will help2

Revision ID: f4f1edcbcc0f
Revises: 4497c0d62379
Create Date: 2024-01-07 00:13:24.940471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f1edcbcc0f'
down_revision = '4497c0d62379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db.sqlite3', 'test_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db.sqlite3', sa.Column('test_field', sa.VARCHAR(length=1), nullable=True))
    # ### end Alembic commands ###
